// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavbypxoffnidfawlzfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdmJ5cHhvZmZuaWRmYXdsemZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjM2NDQsImV4cCI6MjA2MDk5OTY0NH0.03QK43lo-TwuWa3jYyDGvhFXo6CDL082boudcrSyJ5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);